### ISSUE TITLE
gilbert watch on windows

### ISSUE THREAD

**Issue by Alysha-94** [funkybob/gilbert#20]
I can run `gilbert render` and `gilbert serve` but `gilbert watch` fails
```
gilbert watch
Searching c:\users\hp\documents\cps\digital_site\venv2\lib\site-packages\gilbert\plugins for plugins...
Loaded plugin: collection
Loaded plugin: markdown
Loaded plugin: scss
Loaded plugin: yaml
Traceback (most recent call last):
  File "C:\Users\HP\Documents\CPS\digital_site\venv2\Scripts\gilbert-script.py", line 11, in <module>
    load_entry_point('gilbert==0.3.3', 'console_scripts', 'gilbert')()
  File "c:\users\hp\documents\cps\digital_site\venv2\lib\site-packages\gilbert\cli.py", line 95, in main
    args.func(args, site)
  File "c:\users\hp\documents\cps\digital_site\venv2\lib\site-packages\gilbert\cli.py", line 37, in handle_watch
    site.watch()
  File "c:\users\hp\documents\cps\digital_site\venv2\lib\site-packages\gilbert\site.py", line 143, in watch
    import inotify.adapters
  File "c:\users\hp\documents\cps\digital_site\venv2\lib\site-packages\inotify\adapters.py", line 11, in <module>
    import inotify.calls
  File "c:\users\hp\documents\cps\digital_site\venv2\lib\site-packages\inotify\calls.py", line 4, in <module>
    import inotify.library
  File "c:\users\hp\documents\cps\digital_site\venv2\lib\site-packages\inotify\library.py", line 8, in <module>
    instance = ctypes.cdll.LoadLibrary(_FILEPATH)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

**Comment by funkybob** [comment]
The implementation for "watch" was written only for inotify compatible OSs as a matter of expediency.

Probably best to remove it, make it a plugin [hmm... need a plugin pattern for command line tools..] and document a better, more general purpose solution.

**Comment by shuttle1987** [comment]
I think it makes sense to just keep it as is for now with a warning that it doesn't work on Windows

**Comment by funkybob** [comment]
https://github.com/watchexec/watchexec

This seems to be the recommended general purpose solution. If you feel like giving it a go, it seems "watchexec -i docs gilbert render" would be the right invocation.

If it works, could you please provide some documentation?

**Comment by shuttle1987** [comment]
That looks like a promising tool. Would be happy to write docs.

**Comment by Alysha-94** [comment]
> If you feel like giving it a go, it seems "watchexec -i docs gilbert render" would be the right invocation.

Great thanks, I have tried this out and it works fine. I'm happy to provide some docs
