### ISSUE TITLE
Unicode issue in file doesn't indicate location of problematic file

### ISSUE THREAD

**Issue by shuttle1987** [funkybob/gilbert#24]
Take for example this:

```
$ gilbert render
Searching /home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/plugins for plugins...
Loaded plugin: collection
Loaded plugin: scss
Loaded plugin: markdown
Loaded plugin: yaml
Loaded local plugins.
Found 2 content objects.
Traceback (most recent call last):
  File "/home/janis/digital_site/venv/bin/gilbert", line 11, in <module>
    load_entry_point('gilbert==0.3.3', 'console_scripts', 'gilbert')()
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/cli.py", line 101, in main
    args.func(args, site)
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/cli.py", line 30, in handle_render
    site.render()
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/site.py", line 104, in render
    self.load_pages()
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/site.py", line 115, in load_pages
    self.pages.load(self.pages_dir)
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/collection.py", line 55, in load
    self.load(item, root)
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/collection.py", line 53, in load
    self._items[name] = self.load_file(item, name=name)
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/collection.py", line 62, in load_file
    data, meta = load_func(path)
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/plugins/yaml.py", line 10, in load_yaml
    loader = yaml.Loader(fin)
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/yaml/loader.py", line 44, in __init__
    Reader.__init__(self, stream)
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 386: invalid start byte
```

**Comment by funkybob** [comment]
Can you please try the following and see if it's more useful:
```
diff --git a/src/gilbert/collection.py b/src/gilbert/collection.py
index 44c3d63..b260288 100644
--- a/src/gilbert/collection.py
+++ b/src/gilbert/collection.py
@@ -57,7 +57,10 @@ class Collection:
     def load_file(self, path: Path, name: str):
         ext = path.suffix.lstrip('.')
 
-        load_func = self._loaders.get(ext, load_raw)
+        try:
+            load_func = self._loaders.get(ext, load_raw)
+        except Exception as e:
+            raise RuntimeError(f"Error loading file: {path}") from e
 
         data, meta = load_func(path)
```

**Comment by shuttle1987** [comment]
After those changes I get this traceback:

```
$ gilbert render
Searching /home/janis/gilbert/src/gilbert/plugins for plugins...
Loaded plugin: collection
Loaded plugin: scss
Loaded plugin: markdown
Loaded plugin: yaml
Loaded local plugins.
Found 2 content objects.
Traceback (most recent call last):
  File "/home/janis/digital_site/venv/bin/gilbert", line 11, in <module>
    load_entry_point('gilbert', 'console_scripts', 'gilbert')()
  File "/home/janis/gilbert/src/gilbert/cli.py", line 94, in main
    args.func(args, site)
  File "/home/janis/gilbert/src/gilbert/cli.py", line 39, in handle_render
    site.render()
  File "/home/janis/gilbert/src/gilbert/site.py", line 22, in _inner
    return method(self, *args, **kwargs)
  File "/home/janis/gilbert/src/gilbert/site.py", line 136, in render
    self.load_pages()
  File "/home/janis/gilbert/src/gilbert/site.py", line 22, in _inner
    return method(self, *args, **kwargs)
  File "/home/janis/gilbert/src/gilbert/site.py", line 150, in load_pages
    self.pages.load(self.pages_dir)
  File "/home/janis/gilbert/src/gilbert/collection.py", line 55, in load
    self.load(item, root)
  File "/home/janis/gilbert/src/gilbert/collection.py", line 53, in load
    self._items[name] = self.load_file(item, name=name)
  File "/home/janis/gilbert/src/gilbert/collection.py", line 66, in load_file
    data, meta = load_func(path)
  File "/home/janis/gilbert/src/gilbert/plugins/yaml.py", line 10, in load_yaml
    loader = yaml.Loader(fin)
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/yaml/loader.py", line 44, in __init__
    Reader.__init__(self, stream)
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 386: invalid start byte
```

**Comment by shuttle1987** [comment]
Note that these tracebacks are NOT identical beyond the different install path:

Before:
```
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/collection.py", line 62, in load_file
    data, meta = load_func(path)
```

After:
```
  File "/home/janis/gilbert/src/gilbert/collection.py", line 66, in load_file
    data, meta = load_func(path)
```

Note the line is different now

**Comment by funkybob** [comment]
The line number changed because the code changed.

But it should also have reported the RuntimeError... odd.

**Comment by shuttle1987** [comment]
> But it should also have reported the RuntimeError... odd.

Hence my post showing that the code *did* change. Perhaps its because getting the `load_func` succeeds but calling it still does not? The failure in both cases is still the line:

```python
        data, meta = load_func(path)
```

Should it instead be doing the exception block around this line?

**Comment by funkybob** [comment]
Blah.. yes.. absolutely it should :)

**Comment by funkybob** [comment]
Obviously it's not the ideal "pretty" output we'd want for a loader error, but it should report which file it was, at least.
