### ISSUE TITLE
Can't `gilbert watch` on macOS

### ISSUE THREAD

**Issue by aapeliv** [funkybob/gilbert#25]
Is `inotify` not supported under macOS?

```
$ gilbert watch
Searching /Users/aapeli/git/cps/digital_site/venv/lib/python3.7/site-packages/gilbert/plugins for plugins...
Loaded plugin: yaml
Loaded plugin: markdown
Loaded plugin: scss
Loaded plugin: collection
Loaded local plugins.
Traceback (most recent call last):
  File "/Users/aapeli/git/cps/digital_site/venv/bin/gilbert", line 11, in <module>
    load_entry_point('gilbert==0.3.3', 'console_scripts', 'gilbert')()
  File "/Users/aapeli/git/cps/digital_site/venv/lib/python3.7/site-packages/gilbert/cli.py", line 95, in main
    args.func(args, site)
  File "/Users/aapeli/git/cps/digital_site/venv/lib/python3.7/site-packages/gilbert/cli.py", line 37, in handle_watch
    site.watch()
  File "/Users/aapeli/git/cps/digital_site/venv/lib/python3.7/site-packages/gilbert/site.py", line 143, in watch
    import inotify.adapters
  File "/Users/aapeli/git/cps/digital_site/venv/lib/python3.7/site-packages/inotify/adapters.py", line 11, in <module>
    import inotify.calls
  File "/Users/aapeli/git/cps/digital_site/venv/lib/python3.7/site-packages/inotify/calls.py", line 39, in <module>
    inotify_init = _LIB.inotify_init
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x1179d9ff0, inotify_init): symbol not found
```

**Comment by aapeliv** [comment]
I see this is mentioned in the FAQ regarding `watch` on Windows.

**Comment by funkybob** [comment]
Correct - inotify appears to be a Linux only API.
