### ISSUE TITLE
Filename of failing validation

### ISSUE THREAD

**Issue by shuttle1987** [funkybob/gilbert#30]
Consider a schema that has a boolean for draft:

```python
class Page(Templated, Content):
    in_menu: bool = True
    call_to_action_text: str
```
Then this file:
```
title: Home
in_menu: False
---

We give high-performing companies the tools they need to compete in the digital age, from skills development and automation to communications and strategy expertise.
```
Will give the following traceback

```
Traceback (most recent call last):
  File "/home/janis/digital_site/venv/bin/gilbert", line 11, in <module>
    load_entry_point('gilbert==0.3.4', 'console_scripts', 'gilbert')()
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/cli.py", line 94, in main
    args.func(args, site)
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/cli.py", line 39, in handle_render
    site.render()
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/site.py", line 22, in _inner
    return method(self, *args, **kwargs)
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/site.py", line 184, in render
    self.load_pages()
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/site.py", line 22, in _inner
    return method(self, *args, **kwargs)
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/site.py", line 198, in load_pages
    self.pages.load(self.pages_dir)
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/collection.py", line 53, in load
    self._items[name] = self.load_file(item, name=name)
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/collection.py", line 67, in load_file
    obj = self.default_type.create(name, self.site, data=data, meta=meta)
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/content.py", line 52, in create
    return klass(name, site, data=data, meta=meta)
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/content.py", line 27, in __init__
    super().__init__(**meta)
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/schema.py", line 160, in __init__
    setattr(self, name, value)
  File "/home/janis/digital_site/venv/lib/python3.7/site-packages/gilbert/schema.py", line 133, in __set__
    raise ValueError(f'{instance.__class__.__name__}.{self.name} does not accept value {value !r}')
ValueError: Page.in_menu does not accept value ['False']
```
I'm thinking that it may be helpful here to report on the filename that contained the non-validating metadata.

**Comment by shuttle1987** [comment]
Also here's the menu.yaml file:
```
content_type: Collection
filter_by:
  all:
    - attr: ['in_menu']
---
```

**Comment by funkybob** [comment]
I've just tried to replicate this locally, and did not trigger an error.

1. created new project
2. put your Page class into plugins.py
3. created pages/fail.yml
4. ran "gilbert render"

```
$ gilbert render
Searching /.../gilbert/plugins for plugins...
Loaded plugin: markdown
Loaded plugin: collection
Loaded plugin: yaml
Loaded plugin: scss
Loaded plugin: asset_bundle
Loaded local plugins.
Found 0 content objects.
Found 1 pages.
Rendering fail.yml ...
Template for default.html not found: ['default.html']
```

Which version of Gilbert are you using?

[also, overridding Page wasn't something I had thought of - neat!]

**Comment by shuttle1987** [comment]
So it turns out that the issue here was that the loader was passing the field `in_menu: False` over unprocessed as `{in_menu: 'False'}` and that was causing the schema to fail validation since it was expecting a boolean but getting a string.

I fixed this over on the loader in https://github.com/shuttle1987/gilbert-frontmatter-markdown/pull/2

Given the source of this appeared to be a bug with my loader code this issue may be invalid, unless there's some error reporting you'd like to add in here?

I'm not exactly sure how I should be making a test case for this though... (and I'd like to make a couple of tests)

**Comment by shuttle1987** [comment]
I think this issue came up with this exact commit version: https://github.com/funkybob/gilbert/pull/29/commits/57614be95207cab7495e93263cd63ca381ee4a21

I had to work off that commit since it lets me use the alternative loader.

**Comment by funkybob** [comment]
Can we consider this issue resolved now?

**Comment by shuttle1987** [comment]
I believe this is not a bug in Gilbert but rather was in my loader, I'll reopen if not
